name: CI
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go test -covermode=atomic -race -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          args: --timeout=10m --verbose
      - run: go install ./cmd/vexllm
